- id: gh-pkg-rollout
  execute-command: "/var/scripts/gh-pkg-rollout.sh"
  command-working-directory: "/app"
  trigger-rule:
    and:
      - match:
          type: value
          value: registry_package
          parameter:
            source: header
            name: X-GitHub-Event
      - match:
          type: payload-hmac-sha256
          secret: '{{ getenv "WEBHOOK_SECRET" }}'
          parameter:
            source: header
            name: X-Hub-Signature-256
      - match:
          type: value
          value: '{{ getenv "APP_IMAGE" }}'
          parameter:
            source: payload
            name: registry_package.package_version.package_url
