name: Release

on:
  push:
    branches: ["trunk"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      released: ${{ steps.semantic.outputs.new_release_published }}
      version: ${{ steps.semantic.outputs.new_release_version }}
      tag: ${{ steps.semantic.outputs.new_release_git_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Install dependencies
        run: |
          npm install -D conventional-changelog-eslint

      - name: Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build-and-push:
    needs: release
    if: needs.release.outputs.released == 'true'
    uses: ./.github/workflows/publish.yaml
    with:
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
