name: Release

on:
  push:
    branches: ["trunk"]
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          check-latest: true

      - name: Install dependencies
        run: |
          npm install -D conventional-changelog-conventionalcommits

      - name: Release
        id: semantic
        env:
          # Using a PAT instead of GITHUB_TOKEN allows the publish workflow to pickup when this action creates a release
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_PAT }}
          # DEBUG: semantic-release:*
        run: npx semantic-release
